In [32]:
import pandas as pd

In [33]:
# Usa el metodod pd.read_csv() para descargar dataframe
# Podemos cargar archivos .csv, pero también archivos .zip que contienen archivos .csv
# Cargar el archivo 'titles.csv'
df = pd.read_csv('titles.csv')

In [35]:
# Echa un vistazo rápido a las primeras veinte entradas de dataframe
df.head(20)

                             title  year  rating  votes
0                   Spanish Fiesta  2019     6.9     29
1           La tierra de los toros  2000     5.4     14
2                    Dama de noche  1993     6.0     25
3                       Frivolinas  2014     5.6     19
4                     Mya ga naing  1996     7.5     21
5         El huésped del sevillano  1970     6.8     11
6                   Kate & Leopold  2001     6.4  81684
7               Muhomatsu no issho  2008     7.3    108
8      Another Time, Another Place  1983     6.5    305
9               Let There Be Light  1980     7.5   1799
10                   Habla, mudita  1973     6.3    149
11                         Nagarik  1977     7.5    202
12                 I Eat Your Skin  1971     3.5   1445
13                    Lash of Lust  1972     2.6     32
14          La rosa de los vientos  1983     4.9     21
15    Auliban, the Seller of Rings  1973     7.0    155
16                 Bruce's Fingers  1976     5.0    179
17                     Born in '45  1990     6.4    239
18                 Satan's Harvest  1970     3.8    150
19  Wenn du groß bist, lieber Adam  1990     6.7     34

In [36]:
### edTest(test_entries) ###
# La función len() se puede usar para ver el número de filas en su marco de datos
# Encontrar las filas en el dataframe original
entries = len(df)
print(entries)

213665

In [37]:
# .shape da el número total de filas y columnas
# comprobar la forma del dataframe original
shape = df.shape
print(shape)

(213665, 4)

In [38]:
# usa .columns para ver las columnas en dataframe
cols = df.columns
print(cols)

Index(['title', 'year', 'rating', 'votes'], dtype='object')

In [39]:
# puede cambiar las columnas a listas nativas de python usando la funcion  .tolist()
col_list = df.columns.tolist()
print(col_list)

['title', 'year', 'rating', 'votes']

In [40]:
# cambiar el nombre de la columna final de 'votes' a 'num_votes'
col_list[-1] = 'num_votes'
print(col_list)

['title', 'year', 'rating', 'num_votes']